apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Aaron's Backstage Application
  description: An example of a Backstage application.
  # Example for optional annotations
  annotations:
    backstage.io/techdocs-ref: dir:.
    # github.com/project-slug: backstage/backstage
spec:
  type: website
  owner: john@example.com
  lifecycle: experimental
